build-ubuntu16:
  image: gitlab.flux.utah.edu:4567/a3/vmi:ubuntu16
  script:
  - autoconf
  - mkdir build install
  - cd build
  - CFLAGS="-I/usr/lib/include/distorm3" ../configure --prefix=`readlink -f ../install` --with-elfutils=/opt/elfutils --disable-asm
  - make
  - make install
  only:
  - master
  
pages:
  image: gitlab.flux.utah.edu:4567/a3/vmi:docbuilder
  script:
  - cd doc
  - make
  - cd ..
  - ln -s doc public
  artifacts:
    paths:
    - public/
