testing:
  script:
  - autoconf
  - mkdir build install
  - cd build
  - ../configure --prefix=`readlink -f ../install`
  - make
  - make install
  only:
  - master
  
pages:
  script:
  - cd doc
  - make
  - cd ..
  - ln -s doc public
  artifacts:
    paths:
    - public/
